# Site settings
title: Portfolio Camilo D. Salinas
description: This is my Portfolio using GitHub Pages
# baseurl: "/" # the subpath of your site, e.g. /blog
url: "https:/javidiazs.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Camilo Diaz Salinas
user_title: Data Engineer • Data Scientist • Data Analyst
email: ing.javidiaz@gmail.com
twitter_username: camilodiazs_
github_username: JavierdiazS
gplus_username: camilo-diaz-salinas

# Google-analytics
google-analytics:
  id: "UA-98210758-2"

exclude: ['package.json', 'src' , 'node_modules']
